### ISSUE TITLE
HtmlFragmentsSupplier to be able to consume 302 response with no html body

### ISSUE THREAD

**Issue by ub1k24** [Knotx/knotx-fragments#161]
**Is your feature request related to a problem? Please describe.**
`HtmlFragmentsSupplier` processes 302 same as 200 responses  which makes it fail on the lack of html body in the response

**Describe the solution you'd like**
`HtmlFragmentsSupplier` should have an ability to pass with no error 302 responses directly through to further handlers

**Describe alternatives you've considered**
`HtmlFragmentsSupplier` could be configurable to `allowEmpty` html body - with a config flag

**Additional context**
This causes AEM integration fail on authoring, whenever user accesses a page through knotx when not logged in

**Comment by tomaszmichalak** [comment]
In scope:
- define a model for options
- we can make the dynamic fragment regexp configurable: `"<knotx:(?<type>\\w+)(?<attributes>.*?[^>])>(?<body>.*?)</knotx:\\1>"` with tree predefined groups: `type`, `attributes` and `body`
- generate adocs
- update README and CHANGELOG.

**Comment by Skejven** [comment]
I reviewed the logic from the `HtmlFragmentsSupplier` one more time. And I must admit I find it quite bad decision to throw an exception when supplier is not able to produce any fragments.
I guess that's too much responsibility, which should be handled somewhere else (e.g. at the Repository Connector level).
I'd suggest to remove the check for empty `body` and just produce an empty list of fragments, when the supplier is not able to provide anything meaningful from the request context (client response).
@tomaszmichalak , @ub1k24 WDYT?

**Comment by ub1k24** [comment]
From my perspective it's perfectly fine to do as you say. This was my initial thought that `HtmlFragmentsSupplier` should not fail on empty `body`.

**Comment by Skejven** [comment]
There is one more logic to consider.
Currently [`FragmentsAssemblerHandler`](https://github.com/Knotx/knotx-fragments/blob/2.2.0/assembler/src/main/java/io/knotx/fragments/assembler/FragmentsAssemblerHandler.java#L82) sets status code `200` when merging fragments.
It wasn't a problem previously, when there was no body and exception was thrown in the `HtmlFragmentsSupplier`. Currently, when empty fragments list is processed by `FragmentsAssemblerHandler` it still overrides the status code (SC) to `200`.

I can think of following scenarios to update that logic, so that `302` is returned in the server response:

1. Update `FragmentsAssemblerHandler` SC logic
	- when request context contains SC (in client response) - use that SC
	- otherwise (no SC in cilent reposnse) set `200` only when body is not empty (case for API Gateway & Web API)

2. Set `200` in client response at the begining of processing and remove logic for SC from assemblelr

3. Update `ResponseWriterHandler` (exactly [`ServerResponse`](https://github.com/Knotx/knotx-server-http/blob/2.2.0/core/src/main/java/io/knotx/server/handler/http/response/writer/ServerResponse.java)) logic to set SC according to:
	- if there is SC in clientResponse - use that SC
	- otherwise if there is body and no SC -> `200`
	- otherwise (no body, no SC) -> `500`

What is worth remembering, any Handler can modify the clientResponse SC (currently there are 3 such handlers: both repo connector, and assembler).
I hesitate between options (1) (change scope limited to fragments repository) and (3) (looks like a proper place to have SC logic in one place).
